---
- name: E-comm demo – create dirs & user
  hosts: all
  become: true
  vars:
    app_user: ecomm
    app_dirs: [/opt/ecomm, /opt/ecomm/bin, /opt/ecomm/data]
  tasks:
    - name: Ensure user exists
      ansible.builtin.user:
        name: "{{ app_user }}"
        shell: /bin/bash
    - name: Create directories
      ansible.builtin.file:
        path: "{{ item }}"
        state: directory
        owner: "{{ app_user }}"
        group: "{{ app_user }}"
        mode: '0755'
      loop: "{{ app_dirs }}"
