---
- name: Install PHP on Debian/Ubuntu
  ansible.builtin.apt:
    name: [php, libapache2-mod-php]
    state: present
    update_cache: yes
  when: ansible_facts['os_family'] == 'Debian'

- name: Install PHP on RedHat/Amazon
  ansible.builtin.yum:
    name: [php, php-cli]
    state: present
  when: ansible_distribution == 'Amazon' or ansible_facts['os_family'] == 'RedHat'

- name: Deploy PHP index
  ansible.builtin.copy:
    dest: /var/www/html/index.php
    mode: '0644'
    content: |
      <?php phpinfo(); ?>

- name: Ensure Apache uses index.php
  ansible.builtin.lineinfile:
    path: "{{ (ansible_facts['os_family'] == 'Debian') | ternary('/etc/apache2/mods-enabled/dir.conf','/etc/httpd/conf/httpd.conf') }}"
    regexp: '^DirectoryIndex'
    line: "DirectoryIndex index.php index.html"
  notify: restart apache
